name: 🔌 Bug Report - API
description: Backend API bug jelentése
title: "[BUG-API] "
labels: ["bug", "api"]
body:
  - type: markdown
    attributes:
      value: |
        Köszönjük, hogy jelentetted a bugot! Kérlek, töltsd ki az alábbi mezőket részletesen.
        
        **Bug ID formátum:** BUG-API-XXX (automatikusan generálódik)

  - type: dropdown
    id: priority
    attributes:
      label: Prioritás
      description: Milyen fontosságú ez a bug?
      options:
        - P1 - Critical (Azonnali javítás szükséges)
        - P2 - High (Fontos, de nem kritikus)
        - P3 - Medium (Közepes fontosság)
        - P4 - Low (Alacsony prioritás)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Súlyosság
      description: Milyen súlyos a bug hatása?
      options:
        - Critical - Alkalmazás nem használható
        - High - Fő funkció nem működik
        - Medium - Funkció részben működik
        - Low - Kisebb probléma, workaround létezik
    validations:
      required: true

  - type: dropdown
    id: bug_type
    attributes:
      label: Bug Típusa
      description: Milyen típusú bug?
      options:
        - Bug - Új bug
        - Regression - Korábban működött, most nem
        - Performance - Teljesítmény probléma
        - Security - Biztonsági probléma
    validations:
      required: true

  - type: input
    id: endpoint
    attributes:
      label: API Endpoint
      placeholder: /api/sources
    validations:
      required: true

  - type: dropdown
    id: http_method
    attributes:
      label: HTTP Metódus
      options:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Leírás
      description: Részletes leírás a bugról
      placeholder: |
        Mit csinál rosszul az API?
        Mi a várt viselkedés?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Környezet
      description: Milyen környezetben jelentkezett a bug?
      placeholder: |
        - Backend verzió: 0.1.0
        - Python verzió: 3.11
        - Docker verzió: 24.0
        - MongoDB verzió: 6.0
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Lépések a hiba reprodukálásához
      description: Pontos lépések, hogyan lehet újra előidézni a bugot
      placeholder: |
        1. API hívás: POST /api/sources
        2. Request body: {...}
        3. ...
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: Aktuális Eredmény
      description: Mi történik most (hibás viselkedés)
      placeholder: |
        - HTTP státusz kód: 500
        - Response body: {...}
        - Backend logok
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: Elvárt Eredmény
      description: Mi kellene, hogy történjen?
      placeholder: |
        - Helyes viselkedés leírása
        - HTTP státusz kód
        - Response body
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Backend Logok
      description: Backend logok részletei (ha elérhető)
      placeholder: |
        [Ide kerülnek a logok]
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: További Információk
      description: Bármi más, ami releváns lehet
      placeholder: |
        - Javítási javaslat (opcionális)
        - Kapcsolódó issue-k
        - Stb.
    validations:
      required: false





