name: 🔒 Bug Report - Biztonság
description: Biztonsági bug jelentése
title: "[BUG-SEC] "
labels: ["bug", "security"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **FONTOS:** Biztonsági bugok esetén lehetőleg ne kommenteld publikus helyen!
        
        Köszönjük, hogy jelentetted a biztonsági problémát! Kérlek, töltsd ki az alábbi mezőket részletesen.

  - type: dropdown
    id: priority
    attributes:
      label: Prioritás
      options:
        - P1 - Critical (Azonnali javítás szükséges)
        - P2 - High
        - P3 - Medium
        - P4 - Low
    validations:
      required: true

  - type: dropdown
    id: security_type
    attributes:
      label: Biztonsági Típus
      options:
        - Authentication / Authorization
        - Data Leakage
        - SQL Injection
        - XSS (Cross-Site Scripting)
        - CSRF
        - Secrets Exposure
        - API Security
        - Input Validation
        - Egyéb
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Leírás
      placeholder: Részletes leírás a biztonsági problémáról
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Hatás
      placeholder: Mi a potenciális hatása ennek a problémának?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Lépések a hiba reprodukálásához
      description: ⚠️ Ne tartalmazzon valós bizalmas adatokat!
    validations:
      required: true

  - type: textarea
    id: recommendation
    attributes:
      label: Javasolt Megoldás
      description: Van-e ötleted a megoldásra?
    validations:
      required: false

