name: ✅ Bug Report - Fact-checking
description: Fact-checking modul bug jelentése
title: "[BUG-FACTCHECK] "
labels: ["bug", "factcheck"]
body:
  - type: markdown
    attributes:
      value: |
        Köszönjük, hogy jelentetted a bugot! Kérlek, töltsd ki az alábbi mezőket részletesen.

  - type: dropdown
    id: priority
    attributes:
      label: Prioritás
      options:
        - P1 - Critical
        - P2 - High
        - P3 - Medium
        - P4 - Low
    validations:
      required: true

  - type: dropdown
    id: factcheck_component
    attributes:
      label: Fact-check Komponens
      options:
        - Claim Extractor (Állítások kinyerése)
        - Source Matcher (Források összevetése)
        - Reference Finder (Hivatkozások keresése)
        - Discrepancy Detector (Eltérések azonosítása)
        - Report Generator (Jelentés generálás)
        - NLP Processing
        - Egyéb
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Leírás
      placeholder: Mit csinál rosszul a fact-checking?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Lépések a hiba reprodukálásához
    validations:
      required: true

  - type: textarea
    id: actual_result
    attributes:
      label: Aktuális Eredmény
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: Elvárt Eredmény
    validations:
      required: true



